<a href="https://colab.research.google.com/github/jprachir/deep-learning-basics/blob/main/data_manipulation_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>



> data manipulation
1. mathematical operations
1. broadcasting
1. slicing, indexing
1. memory saving
1. conversion to other python objects



In [24]:
import torch
import numpy as np

In [6]:
x = torch.tensor((2))
x.shape

torch.Size([])

In [47]:
#hack: 4 dimensional because 4 sq brackets
x = torch.zeros((2,2,3,2)) 
print(x)
x.shape

tensor([[[[0., 0.],
          [0., 0.],
          [0., 0.]],

         [[0., 0.],
          [0., 0.],
          [0., 0.]]],


        [[[0., 0.],
          [0., 0.],
          [0., 0.]],

         [[0., 0.],
          [0., 0.],
          [0., 0.]]]])


torch.Size([2, 2, 3, 2])

In [51]:
y = torch.zeros((2,3,4)) #3d, 2 matrices each of (3x4) matrix
y

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [54]:
#5d, 2 matrix of 2x(1x(5x(3x4))))
z = torch.zeros((2,1,5,3,4))   
z

tensor([[[[[0., 0., 0., 0.],
           [0., 0., 0., 0.],
           [0., 0., 0., 0.]],

          [[0., 0., 0., 0.],
           [0., 0., 0., 0.],
           [0., 0., 0., 0.]],

          [[0., 0., 0., 0.],
           [0., 0., 0., 0.],
           [0., 0., 0., 0.]],

          [[0., 0., 0., 0.],
           [0., 0., 0., 0.],
           [0., 0., 0., 0.]],

          [[0., 0., 0., 0.],
           [0., 0., 0., 0.],
           [0., 0., 0., 0.]]]],



        [[[[0., 0., 0., 0.],
           [0., 0., 0., 0.],
           [0., 0., 0., 0.]],

          [[0., 0., 0., 0.],
           [0., 0., 0., 0.],
           [0., 0., 0., 0.]],

          [[0., 0., 0., 0.],
           [0., 0., 0., 0.],
           [0., 0., 0., 0.]],

          [[0., 0., 0., 0.],
           [0., 0., 0., 0.],
           [0., 0., 0., 0.]],

          [[0., 0., 0., 0.],
           [0., 0., 0., 0.],
           [0., 0., 0., 0.]]]]])

In [39]:
x = np.array([1,2,4,8])
y = np.array([2,2,2,1.9])
x + y, x*y, x/y, x-y, x ** y, np.exp(y)
np.mean(y)

1.975

In [81]:
x = np.array([1,1])
y = np.array([2,1])

print(x==y)
print(x > y)
print(y>x)

[False  True]
[False False]
[ True False]


In [68]:
before = id(y)
print(before)
y = y + x
id(y) == before
id(y)

139856743445808


139856742906656

In [78]:
#reduce memory allocation so inplace operation
Z = np.zeros_like((2,1))
print(id(Z))
Z[:] = x + y
print(id(Z))

139856744017792
139856744017792
